### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by nsdmrkl46** [semihimes/Arduino-Turkce-Karakter#1]
Öncelikle çok güzel ve önemli bir çalışma olmuş ellerinize sağlık. Fakat Arduino ide üzerinden ESP32 programlama yaparken kütüphane çalışmamaktadır. Sebebi ne olabilir herhangi bir çözümü var mı? yardımlarınız için çok teşekkür ederim

**Comment by semihimes** [comment]
ESP32 kullanmadım hiç. Karşılaştığınız hata nedir? Kütüphane standart arduino lcd kütüphaneleri üzerine kuruldu, esp32 farklı bir kütüphane kullanıyorsa bu kütüphaneyi düzenlemek gerekebilir. Yapılan değişiklikleri "README" dosyasına ekledim. Yardımcı olabilir.

**Comment by semihimes** [comment]
ESP32 ile ilgili sorunun arduino lcd referans kütüphanesindeki "delayMicroseconds(50000);" kodu olabilir. Bir kullanıcı aşağıdaki bağlantıda ESP8266 için sorunu tespit etmiş ve kütüphanenin beklendiği gibi çalışması için uygulama önerisi verilmiş. ESP32 için de bir çözüm olabilir bu.
https://github.com/arduino-libraries/LiquidCrystal/issues/1

**Comment by semihimes** [comment]
ESP32 farklı dosyalarla çalışıyormuş. Bunun için ayrı bir kütüphane düzenledim. profilimde bulunabilir.
